// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BLL.DAL;

[Table("Comment")]
public partial class Comment
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PublishDate { get; set; }

    public int? BlogId { get; set; }

    public int? UserId { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("Comments")]
    public virtual Blog Blog { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Comments")]
    public virtual User User { get; set; }
}